spring:
  application:
    name: myapp
  profiles:
    active: local

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  show-actuator: false

management:
  server:
    port: 8080 # Actuator 포트 설정
  endpoints:
    web:
      exposure:
        include: "*" # Prometheus endpoint 노출
  endpoint:
    health:
      show-details: always # Health endpoint 상세 정보 노출
      probes:
        enabled: true # LivenessState, ReadinessState 활성화
  health:
    livenessState:
      enabled: true # LivenessState 활성화
    readinessState:
      enabled: true # ReadinessState 활성화
  metrics:
    enable:
      all: true # 모든 기본 메트릭 활성화
      
logging:
  level:
    '[com.sk.skala.myapp.controller]': DEBUG
    '[com.sk.skala.myapp.service]': DEBUG
