spring.application.name=day2
spring.ai.openai.api-key=${OPENAI_API_KEY:not-set}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small

lab2.rag.chunk-size=250
lab2.rag.overlap-percent=0
lab2.rag.top-k=5
lab2.rag.similarity-threshold=0.4

springdoc.swagger-ui.path=/swagger-ui.html
